apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linux-edr-sensor.fullname" . }}
  labels:
    {{- include "linux-edr-sensor.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  config.json: |
    {{- include "linux-edr-sensor.config" . | fromYaml | toJson | nindent 4 }}