apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linux-edr-sensor.fullname" . }}
  labels:
    {{- include "linux-edr-sensor.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  config.json: |
    {{ if .Values.overrideConfig -}}
    {{- with .Values.customConfig -}}
    {{ . | toJson }}
    {{- end -}}
    {{- else -}}
    {
      "access_token": {{ required "A valid access token is required." .Values.defaultConfig.accessToken | quote }},
      "offload_target": "Outpost",
      "outpost_auth_token": {{ required "A valid Outpost auth token is required." .Values.defaultConfig.outpostAuthToken | quote }}
      {{- if .Values.defaultConfig.telemetrySource }}
      ,"telemetry": {"source":{{ .Values.defaultConfig.telemetrySource | quote }}}
      {{- end }}
      {{- if .Values.defaultConfig.reportingTags }}
      ,"reporting_tags": {{ .Values.defaultConfig.reportingTags | toJson }}
      {{- end }}
    }
    {{- end }}