# Default values for Linux EDR sensor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  # -- The image repository to pull from<br>
  # <REPLACE_WITH_YOUR_REGISTRY>/canary_forwarder
  repository: redcanary-forwarder-docker-prod-local.jfrog.io/canary_forwarder
  # -- The policy for fetching images from the repository at runtime.
  pullPolicy: IfNotPresent
  # -- Tag of the image to deploy. Defaults to the app version of the chart.
  tag:

# -- Secret that stores credentials that are used for accessing the container registry
imagePullSecrets: []
  # - name: pullSecret

# -- String to partially override linux-edr-sensor.fullname template (will maintain the release name)
nameOverride: ""
# -- String to fully override linux-edr-sensor.fullname template
fullnameOverride: ""

# -- Additional annotations for the deployed pod(s).
podAnnotations: {}
# -- Additional labels to add to all the resources created by this chart.
labels: {}

# -- Sets the allocated CPU and memory specifications for the pod(s).
resources: {}
  # limits:
  #   cpu: 250m
  #   memory: 512Mi
  # requests:
  #   cpu: 125m
  #   memory: 256Mi

# -- Tolerations allow the pod to be scheduled onto nodes with specific taints.
# Examples can be used if needed to tolerate all taints, or for well-known control-plane taints.
tolerations: []
  # - key:
  #   operator: Exists
  # - key: node-role.kubernetes.io/control-plane
  #   operator: Exists
  #   effect: NoSchedule
  # - key: node-role.kubernetes.io/master
  #   operator: Exists
  #   effect: NoSchedule

# -- When you specify a nodeSelector, the Kubernetes scheduler will only consider nodes that match the labels you have specified. nodeAffinity is preferred see k8s documentations for further detail - https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
nodeSelector: {}
  # kubernetes.io/arch: amd64

# -- Use this to define a custom affinity section, using standard k8s syntax.
affinity: {}
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #       - matchExpressions:
  #           - key: kubernetes.io/arch
  #             operator: In
  #             values:
  #               - amd64

# -- Whether or not the DaemonSet's pod should be associated with a ServiceAccount
useServiceAccount: false

# -- If a ServiceAccount is being used, this names it
serviceAccountName: ""

persistence:
  # -- Whether or not persistent storage should be used for the sensor's /var, /tmp and /logs data.
  enabled: true
  # -- The path on the host to use for persistent node state. You must ensure this is not on a mount with the 'noexec' flag. Only used when enabled is set to true.
  nodestateDir: /var/lib/misc/redcanary
  # -- The path on the host to use for persistent tmp storage. Only used when enabled is set to true.
  tmpDir: /tmp
  # -- The path on the host to use for persistent log storage. Only used when enabled is set to true.
  logDir: /var/log

# -- Values used for the default configuration. These will not be used if overrideConfig is set to true.
config:
  # -- Required. Parameter for configuring access token.
  accessToken:
  # -- Required. Parameter for configuring Outpost auth.
  outpostAuthToken:
  # -- Optional. Only required for endpoints where we wish to use the eBPF telemetry collection method.
  telemetrySource: ebpf  # Valid options are audit, ebpf, or subdomain
  # -- Optional. This becomes the value of the "endpoint_reporting_tags" field included in the envelope fields of all telemetry/health files that are offloaded.
  reportingTags:
    # Color: green
    # Shape: square
  # -- Additional configuration options to be passed to the Red Canary Linux EDR Sensor. Please only use when troubleshooting with Red Canary.
  extraOptions:
